server:
  port: 8080

mqtt:
#  broker: tcp://broker.emqx.io:1883
  broker: tcp://60.205.176.65:1883
  username: ''
  password: ''
  client-id: springboot-mqtt

  default-topic: esp8266/send
  additional-topics: esp8266/recv

  qos: 1
  timeout: 30
  keepalive: 60